[package]
name = "AU-Finder" # will be later renamed to Pretzel-Lover
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "signal", "time"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1"
rustls = { version = "0.23", features = ["ring"] }
#tracing = "0.1"
#tracing-subscriber = "0.3"
twilight-model = "0.17"
twilight-http = { version = "0.17", features = ["simd-json"] }
twilight-gateway = { version = "0.17", features = ["simd-json"] }
twilight-util = { version = "0.17", features = ["builder"] }
turso = "0.7"
sea-query = { version = "1.0", features = ["derive", "backend-sqlite"] }

[profile.release]
opt-level = 3
strip = true